'use client';

import { useState, useCallback } from 'react';

const INK = '#0E0E0E';
const PAPER = '#FAF7F2';
const MUTED = '#E9E2D3';

type ReportProps = {
  artistName: string;
  channelState: string;
  headline: string;
  ifIgnored: string | null;
  fixActions: string[];
  nextMove: string;
  missedReach: { title: string; views: number; formats: string[] }[];
  stats: {
    subs: number | null;
    views7d: number | null;
    subs7d: number | null;
    uploads30d: number;
    lastUpDays: number | null;
  };
};

function fmtNum(n: number) {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1) + 'M';
  if (n >= 1_000) return (n / 1_000).toFixed(n >= 10_000 ? 0 : 1) + 'K';
  return String(n);
}

function buildReport(p: ReportProps): string {
  const date = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });

  const lines: string[] = [];

  lines.push(`YOUTUBE CHANNEL REPORT — ${p.artistName.toUpperCase()}`);
  lines.push(date);
  lines.push('');

  // State
  lines.push(`STATE: ${p.channelState}`);
  lines.push(p.headline);
  if (p.ifIgnored) {
    lines.push(`Risk: ${p.ifIgnored}`);
  }
  lines.push('');

  // Stats
  lines.push('CHANNEL SNAPSHOT');
  if (p.stats.subs != null) lines.push(`  Subscribers: ${fmtNum(p.stats.subs)}`);
  if (p.stats.views7d != null) lines.push(`  Views (7d): ${p.stats.views7d >= 0 ? '+' : ''}${fmtNum(p.stats.views7d)}`);
  if (p.stats.subs7d != null) lines.push(`  Subs (7d): ${p.stats.subs7d >= 0 ? '+' : ''}${p.stats.subs7d.toLocaleString()}`);
  lines.push(`  Uploads (30d): ${p.stats.uploads30d}`);
  if (p.stats.lastUpDays != null) lines.push(`  Last upload: ${p.stats.lastUpDays === 0 ? 'today' : `${p.stats.lastUpDays}d ago`}`);
  lines.push('');

  // Fix this week
  if (p.fixActions.length > 0) {
    lines.push('FIX THIS WEEK');
    for (const a of p.fixActions) {
      lines.push(`  → ${a}`);
    }
    lines.push('');
  }

  // Next move
  lines.push('NEXT MOVE');
  lines.push(`  → ${p.nextMove}`);
  lines.push('');

  // Missed reach
  if (p.missedReach.length > 0) {
    lines.push('MISSED REACH');
    for (const v of p.missedReach) {
      lines.push(`  ${v.title} (${fmtNum(v.views)} views)`);
      lines.push(`    Missing: ${v.formats.join(', ')}`);
    }
    lines.push('');
  }

  lines.push('— Generated by YouTube Campaign Coach');

  return lines.join('\n');
}

export default function WatcherReport(props: ReportProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    const text = buildReport(props);
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [props]);

  return (
    <div className="mt-10 flex items-center justify-center">
      <button
        onClick={handleCopy}
        className="px-5 py-2.5 rounded-lg text-[12px] font-bold uppercase tracking-[0.14em] inline-flex items-center gap-2 transition-colors cursor-pointer"
        style={{
          background: copied ? '#E6F8EE' : 'transparent',
          color: copied ? '#0C6A3F' : INK,
          border: `1px solid ${copied ? '#1FBE7A' : MUTED}`,
        }}
      >
        {copied ? (
          <>
            <CheckIcon />
            Copied to clipboard
          </>
        ) : (
          <>
            <ClipboardIcon />
            Generate report
          </>
        )}
      </button>
    </div>
  );
}

function ClipboardIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
